### PR TITLE
NewsWeek Index Page Clone

### PR DESCRIPTION
**Pull request by acushlakoncept**
In this project, I used Twitter’s Bootstrap framework to clone the [NewsWeek.com](https://www.newsweek.com/) website.

> The mobile-first-approach was taken to tackle the design.

I used 
- Bootstrap v4.0 Grid Layout
- Flex order class
- Some CSS Advanced Selectors
- Bootstrap classes that change base on screen sizes. (`col-sm`, `col-md`, `col-lg`, and `col-xl`)
- Got a deeper look into the bootstrap v4 documentation while combining some custom css to achieve the result.

### CODE REVIEW

**Comment by addod19** [comment]
## Pul Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @acushlakoncept, congratulations on building such a great and amazing project :+1: README looks professional and the UI looks awesome, descriptive PR :slightly_smiling_face: However, there are a few modifications we need to implement so we can get our project approved. Let us address the comments below:
- Let us fix the subscribe section and make it better
```Clone``` Mobile version
subfix1
```Original```
subfix
```Footer```, let us make our text bolder like the original
```Clone```
footerfix
```Original```
footerfix1
```Featured stories```, the featured stories come immediately after the Top Story. Currently, we have "heroes of the pandemic" instead
- Kindly delete the mobile.html since it was used for debugging purposes


[OPTIONAL]
- In our next projects, let us try to write our commit messages in the present, for example; add instead of added, fix instead of fixed
- Let us improve semantics by using ```<section>, <article>, <main>``` in our code

Kindly make these changes and submit another code review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo)

**Comment by acushlakoncept** [comment]
Thank you @addod19 for your great feedback, I appreciate.
I have implemented the requested changes.
Thank you.

**Review by sumancrest0001 — APPROVED** [review]
**STATUS: APPROVED :100: :clap: 
Well done @acushlakoncept,**
Your layout looks good and the page is very responsive. You addressed all the mandatory changes requested by the previous TSE. It's a green signal from my side. Now, you can merge and submit the project completion form. All the best with the next project. Furthermore, I have mentioned some nice to have changes. I encourage you to work on them.

mission

**Happy coding !!!**

**Comment by sumancrest0001** [comment]
1. On the mobile screen, these images do not have same height. Have a look :point_down: 
Screenshot from 2020-05-30 21-51-05

2. I encourage you to use more semantic tags instead of just div tags. It helps in debugging also. This [article](https://www.w3schools.com/html/html5_semantic_elements.asp) might be helpful to you.

**Comment by acushlakoncept** [comment]
Thank you @sumancrest0001, the article you suggested helped and thank you for your great feedback.

**Pull request merged**
